["insert OR IGNORE into user (email , password, name, type) values ('carlos@myshoppingapp.com', 'password', 'Carlos Frank', 'admin')"
"insert OR IGNORE into user (email , password, name, type) values ('alice@gmail.com', 'password', 'Alice Williams', 'customer')"
"insert OR IGNORE into user (email , password, name, type) values ('piyush@gmail.com', 'password', 'Piyush Goyal', 'customer')"

"insert or ignore into product_category (id, name, desc, picture) values (1, 'Accessories', 'Jewellary for all kind of occasions !', 'goldnecklace.jpg')"
"insert or ignore into product_category (id, name, desc, picture) values (2, 'Time pieces', 'Stylist wrist watches and clocks', 'blackandwhitewatchpair.jpg')"
"insert or ignore into product_category (id, name, desc, picture) values (3,'Makeup products', 'All branded make up products', 'makeupset.jpg')"
"insert or ignore into product_category (id, name, desc, picture) values (4,'Fashion clothing', 'Tops, shirts, pants, skirts, ethnic wear for men and women', 'dress1.jpg')"
"insert or ignore into product_category (id, name, desc, picture) values (5,'Foot wear', 'All types of slip-ons, ballerinas and shoes', 'shoe2.jpg')" 

"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (1, 1,'Silver bangles with stone settings','bangles silver white stones', 'Silver bangle embedded with white stones.', '100.00$','Jewellary/bangle1.jpg', '5')"   
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (2, 1,'Gold bangles','bangles gold traditional ethnic','24 karat gold bangle with traditional workmanship','1000.00$','Jewellary/bangle2.jpg', '4')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (3, 1,'Gold polished bangles','bangles gold polished ethnic','Rolled god bangles. Ideal to gift to college kids.','400.00$','Jewellary/bangle3.jpg', '1')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (4, 1,'Diamond studded bangles','bangles diamond platinum','Surreal platinum and diamond bangle for your special one!','10000.00$','Jewellary/bangle4.jpg', '5')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (5, 1,'Diamond and saphire studded bangles','bangles diamond saphire blue gold','These diamond and blue sapphire studded gold bangles radiate grace. Ideal for semi-ethnic attire.','350000.00$','Jewellary/bangle5.jpg', '5')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (6, 1,'Emerald studded gold bracelet','bracelet emerald gold green', 'A delicate emerald studded bracelet','550000.00$','Jewellary/bracelet1.jpg', '3')"
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (7, 1,'Silver flower bracelet','bracelet silver flower','A trendy floral patterned silver bracelet!','12000.00$','Jewellary/bracelet2.jpg', '3')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (8, 1,'Pure Gold bracelet','bracelet gold chain interleaved','Simple gold bracelet in interleaved design.','80000.00$','Jewellary/bracelet5.jpg', '3')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (9, 1,'Rhodium plated gold bracelet with emerald and saphire stones','bracelet gold white gold rhodium plated emerald saphire green blue','Exquisite rhodium plated gold bracelet with emerald and sapphire stones','100000.00$','Jewellary/bracelet5.jpg', '5')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (10, 1,'Silver and Pink bracelet','bracelet pink silver','A trendy pink stone studded silver bracelet ideal for college going girls!','20000.00$','Jewellary/bracelet4.jpg', '4')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (11, 1,'Silver danglers','silver earrings danglers','Ethnic silver danglers with ethnic work','20000.00$','Jewellary/earing.jpg', '3')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (12, 1,'Gold danglers','gold earrings danglers','Simple gold danglers.','70000.00$','Jewellary/earing1.jpg', '4')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (13, 1,'Gold star studs with embedded pearls','gold earrings studs star pearls','A moden pearl embedded star shaped gold studs. Looks good with both western and semi ethnic attire!','120000.00$','Jewellary/earing2.jpg', '4')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (14, 1,'Gold pearl drops with diamond','gold earrings drops danglers pearls diamond','A pearl and diamond studded gold danglers!','170000.00$','Jewellary/earing3.jpg', '5')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (15, 1,'Gold danglers with pink stones','gold earrings drops danglers pink','Pink stone studded gold danglers','175000.00$','Jewellary/earing4.jpg', '4')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (16, 1,'Gold pearl drops with diamond','gold earrings drops danglers pearls diamond','A pearl and diamond studded gold danglers!','170000.00$','Jewellary/earing5.jpg', '5')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (17, 1,'diamond studs encased in platinum','platinum studs diamond earrings','A exquisite diamond studded platinum studs. Ideal to gift to her on your anniversary!','300000.00$','Jewellary/earing6.jpg', '4')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (18, 1,'Gold danglers with black stones','gold earrings danglers drops black','Black stone based gold danglers to match any outfit!','100000.00$','Jewellary/earing7.jpg', '4')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (19, 1,'Gold danglers with saphire','gold earrings danglers drops saphire blue','gold earrings danglers drops saphire blue','300000.00$','Jewellary/earing9.jpg', '5')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (20, 1,'Pearl three layer necklace','pearl necklace layered white','pearl necklace layered white','15000.00$','Jewellary/necklace1.jpg', '4')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (21, 1,'Pearl three layer necklace with center black stone','pearl necklace layered white black white','pearl necklace layered white black white','30000.00$','Jewellary/necklace3.jpg', '3')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (22, 1,'Green jade silver necklace','necklace jade green silver','necklace jade green silver','40000.00$','Jewellary/necklace4.jpg', '5')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (23, 1,'Pink jade silver necklace','necklace jade pink silver','necklace jade pink silver','40000.00$','Jewellary/necklace5.jpg', '5')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (24, 1,'Black metal necklace','necklace black metal','necklace black metal','40000.00$','Jewellary/necklace6.jpg', '3')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (25, 1,'Emerald necklace','necklace emerald green','necklace emerald green','49000.00$','Jewellary/necklace7.jpg', '4')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (26, 1,'Black metal necklace','necklace black metal','necklace black metal','40000.00$','Jewellary/necklace8.jpg', '3')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (27, 1,'Saphire necklace','necklace saphire blue','necklace saphire blue','40000.00$','Jewellary/necklace10.jpg', '4')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (28, 1,'Blue jade necklace','necklace jade blue','necklace jade blue','40000.00$','Jewellary/necklace11.jpg', '4')"  
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (29, 1,'Pink jade necklace','necklace jade pink','necklace jade pink','60000.00$','Jewellary/necklace14.jpg', '4')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (30, 1,'Self patterned gold bangles','bangles gold','A pair of beautiful exclusive self patterned kadas. Ideal to go with ethnic wear','60000.00$','Jewellary/bangle7.jpg', '4')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (31, 1,'Traditionally designed self pattern gold bangles','bangles gold','A pair of beautiful exclusive self patterned kadas with elephant motif. Ideal to go with ethnic wear','90000.00$','Jewellary/bangle8.jpg', '5')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (32, 1,'Self patterned gold bangles','bangles gold','A beautiful pair of 24 carat exclusive self patterned kadas. Ideal to go with ethnic wear','60000.00$','Jewellary/bangle9.jpg', '4')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (33, 1,'Self patterned gold bangles','bangles gold','A beautiful pair of 24 carat  exclusive self patterned kadas. Ideal to go with ethnic wear','68000.00$','Jewellary/bangle10.jpg', '5')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (34, 1,'Self patterned gold bangles','bangles gold','A single 22 karat exclusive self patterned kada. Ideal to go with ethnic wear','30000.00$','Jewellary/bangle11.jpg', '2')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (35, 1,'Self patterned gold bangles with minakri work','bangles gold','A single 24 karat exclusive self patterned kada with minakari work','40000.00$','Jewellary/bangle13.jpg', '5')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (36, 1,'Self patterned gold bangles with minakri design','bangles gold','A beautiful pair of 24 carat exclusive self patterned kadas with minakri work','75000.00$','Jewellary/bangle15.jpg', '4')" 
"insert or ignore into product (product_id, category_id, name, search_tag, description, price, pictures, rank) values (37, 1,'Self patterned single gold bangle with minakari design','bangles gold','A exquisitely carved 24 karat exclusive self patterned kada with minakri motif. Ideal to go with ethnic/semi-ethnic wear','55000.00$','Jewellary/bangle16.jpg', '5')" 


"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (1, 'g', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (2, 'go', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (3, 'gol', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (4, 'gold', 0)"

"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (5, 'gold b ', 0)" 
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (6, 'gold ba', 0)" 
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (7, 'gold ban', 0)" 
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (8,  'gold bang', 0)" 
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (9, 'gold bangl', 0)"  
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (10, 'gold bangle', 0)" 
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (11, 'gold bangles', 1)" 

"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (12, 'gold band', 0)"   
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (13, 'gold banda', 0)"  
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (14, 'gold bandan', 0)" 
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (15, 'gold bandana', 1)"

"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (16, 'gold e', 0)" 
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (17, 'gold ea', 0)" 
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (18, 'gold ear', 0)"   
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (19, 'gold earr', 0)"  
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (20, 'gold earri', 0)" 
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (21, 'gold earrin', 0)"   
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (22, 'gold earring', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (23, 'gold earrings', 1)"

"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (24, 'b', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (25, 'bl', 0)"  
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (26, 'blu', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (27,'blue', 0)"

"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (28, 'blue b', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (29, 'blue ba', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (30, 'blue ban', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (31, 'blue bang', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (32, 'blue bangl', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (33, 'blue bangle', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (34, 'blue bangles', 1)"

"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (36, 'blue b', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (37, 'blue br', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (38, 'blue bra', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (39, 'blue brac', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (40, 'blue brace', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (41, 'blue bracel', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (42, 'blue bracele', 0)"
"insert or ignore into auto_suggest_trie (ID,  VALUE, WORDEND) VALUEs (43, 'blue bracelet', 1)"]


 


